version: '3.4'

services:
  app:
    image: go-proxy-server
    container_name: go-proxy-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    # command: ["./go-proxy-server"]